Models/Comment.cs
using System;

namespace VulnerableCoreApp.Models
{
    public class Comment
    {
        public String ID { get; set; }
        public String Username { get; set; }
        public DateTime CreatedAt { get; set; }
        public String Text { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace VulnerableCoreApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewModels/CommentViewModel.cs
using System;

namespace VulnerableCoreApp.ViewModels
{
    public class CommentViewModel
    {
        public String ID { get; set; }
        public String Username { get; set; }
        public DateTime CreatedAt { get; set; }
        public String Text { get; set; }
    }
}

ViewModels/CommentsViewModel.cs
using System;
using System.Collections.Generic;

namespace VulnerableCoreApp.ViewModels
{
    public class CommentsViewModel
    {
        public List<CommentViewModel> Comments { get; set; }
    }
}

Controllers/CrossSiteScriptingController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using VulnerableCoreApp.ViewModels;
using VulnerableCoreApp.Models;
using VulnerableCoreApp.Repository;

namespace VulnerableCoreApp.Controllers
{
    public class CrossSiteScriptingController : Controller
    {
        private ICommentsRepository commentsRepository;
        public CrossSiteScriptingController(ICommentsRepository commentsRepository)
        {
            this.commentsRepository = commentsRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult DemoTypeI()
        {
            CommentsViewModel comments = commentsRepository.GetAll();
            
            return View(comments);
        }

        [HttpPost]
        public IActionResult DemoTypeI(CommentViewModel comment)
        {
            Comment newComment = new Comment();
            newComment.ID = Guid.NewGuid().ToString();
            newComment.Username = "Anonymous";
            newComment.CreatedAt = DateTime.Now;
            newComment.Text = comment.Text;
            commentsRepository.Save(newComment);

            return RedirectToAction("DemoTypeI");
        }

        [HttpPost]
        public IActionResult DemoTypeIDelete(String ID)
        {
            commentsRepository.Delete(ID);

            return RedirectToAction("DemoTypeI");
        }

        [HttpGet]
        public IActionResult DemoTypeII(string query)
        {
            ViewData["query"] = query;
            
            // Disable Chrome browser XSS protection 
            HttpContext.Response.Headers.Add("X-XSS-Protection","0");
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VulnerableCoreApp.Models;

namespace VulnerableCoreApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/CrossSiteScripting/DemoTypeI.cshtml
@model VulnerableCoreApp.ViewModels.CommentsViewModel 
@{ 
    ViewData["Title"] = "Stored XSS (AKA Persistent or Type I)"; 
}

<div class="row">
    <h1 class="text-center">Store and render unencoded HTML markup</h1>
</div>

<div class="row">
  <h2>Example</h2>
</div>
<br />
<div class="row">
  <ul>
    <li>Enter <mark>&lt;script&gt;alert('Test');&lt;/script&gt;</mark> or any other valid Javascript code wrapped inside script tag in comment textarea and submit</li>
  </ul>
</div>
<div class="row">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    <h2>Comments</h2>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Comments) {
            <tr>
                <td>
                    <div class="clearfix">
                        <div class="col-sm-11">
                            <div class="clearfix">
                                <b>@Html.Raw(item.Username)</b> <span>made a post</span>
                            </div>
                            <div class="clearfix">
                                at <small>@Html.Raw(item.CreatedAt)</small>
                            </div>     
                            <div class="clearfix" style="padding: 0.5em">
                                @Html.Raw(item.Text)
                            </div>
                        </div>
                        <div class="col-sm-1">
                            <form asp-controller="CrossSiteScripting" asp-action="DemoTypeIDelete" method="post">
                                <input type="hidden" name="ID" value="@item.ID">
                                <button type="submit" class="btn btn-danger">×</button>
                            </form>
                        </div>                 
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

<div class="row">
  <form asp-controller="CrossSiteScripting" asp-action="DemoTypeI" method="post">
      <div class="form-group">
          <textarea class="form-control" id="Text" name="Text" cols="20" rows="5" placeholder="Comment" style="resize: none"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
<br />
<div class="row">
  <h2>Vulnerable Code</h2>
</div>
<br />
<div class="row">
  <p>Submitted comment is saved (stored) as raw text without sanitization techniques.</p>
  <pre>
    <code class="C#">
        [HttpPost]
        public IActionResult DemoTypeI(CommentViewModel comment)
        {
            Comment newComment = new Comment();
            newComment.ID = Guid.NewGuid().ToString();
            newComment.Username = &quot;Anonymous&quot;;
            newComment.CreatedAt = DateTime.Now;
            newComment.Text = comment.Text;
            commentsRepository.Save(newComment);

            return RedirectToAction(&quot;DemoTypeI&quot;);
        }
    </code>
  </pre>
</div>

<div class="row">
  <p>Application renders comment as raw text, without escaping HTML tags.</p>
  <pre>
    <code class="html">
      &lt;div class=&quot;clearfix&quot; style=&quot;padding: 0.5em&quot;&gt;
          @@Html.Raw(item.Text)
      &lt;/div&gt;
    </code>
  </pre>
</div>

@section Scripts {
<script>hljs.initHighlightingOnLoad();</script>
}

Views/CrossSiteScripting/DemoTypeII.cshtml
<style>
  #search {
    position: fixed;
    top: 0px;
    left: 0px;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.7);

    -webkit-transition: all 0.5s ease-in-out;
    -moz-transition: all 0.5s ease-in-out;
    -o-transition: all 0.5s ease-in-out;
    -ms-transition: all 0.5s ease-in-out;
    transition: all 0.5s ease-in-out;

    -webkit-transform: translate(0px, -100%) scale(0, 0);
    -moz-transform: translate(0px, -100%) scale(0, 0);
    -o-transform: translate(0px, -100%) scale(0, 0);
    -ms-transform: translate(0px, -100%) scale(0, 0);
    transform: translate(0px, -100%) scale(0, 0);

    opacity: 0;
  }

  #search.open {
    -webkit-transform: translate(0px, 0px) scale(1, 1);
    -moz-transform: translate(0px, 0px) scale(1, 1);
    -o-transform: translate(0px, 0px) scale(1, 1);
    -ms-transform: translate(0px, 0px) scale(1, 1);
    transform: translate(0px, 0px) scale(1, 1);
    opacity: 1;
  }

  #search input[type="search"] {
    position: absolute;
    top: 50%;
    width: 100%;
    color: rgb(255, 255, 255);
    background: rgba(0, 0, 0, 0);
    font-size: 60px;
    font-weight: 300;
    text-align: center;
    border: 0px;
    margin: 0px auto;
    margin-top: -51px;
    padding-left: 30px;
    padding-right: 30px;
    outline: none;
  }

  #search .btn {
    position: absolute;
    top: 50%;
    left: 50%;
    margin-top: 61px;
    margin-left: -45px;
  }

  #search .close {
    position: fixed;
    top: 55px;
    right: 15px;
    color: #fff;
    background-color: #428bca;
    border-color: #357ebd;
    opacity: 1;
    padding: 10px 17px;
    font-size: 27px;
  }
</style>
@{ ViewData["Title"] = "Reflected XSS (AKA Non-Persistent or Type II)"; }
<div class="row">
  <h1 class="text-center">Malicious parameter is reflected back to the user</h1>
</div>

<div class="row">
  <h2>Example</h2>
</div>
<br />
<div class="row">
  <ul>
    <li>Click search to open search form</li>
    <li>Enter
      <mark>&lt;script&gt;alert('Test');&lt;/script&gt;</mark> or any other valid Javascript code wrapped inside script tag and
      click search</li>
  </ul>
</div>

<div class="row">
  <a class="btn btn-primary " href="#search">Search</a>
</div>
<br />

<div class="row">
  @if(ViewData["query"] != null) {
  <div class="well text-center">@Html.Raw((string)ViewData["query"])</div>
  } else {
  <div class="well text-center">
    <span>Search Results</span>
  </div>
  }
</div>

<br />
<div class="row">
  <h2>Vulnerable Code</h2>
</div>

<br />
<div class="row">
  <p> Entered Javascript code is sent to the server in GET parameter named
    <i>query.</i>
  </p>
      <pre>
    <code class="C#">
        [HttpGet]
        public IActionResult DemoTypeII(string query)
        {
            ViewData["query"] = query;
            
            // Disable Chrome browser XSS protection 
            HttpContext.Response.Headers.Add("X-XSS-Protection","0");
            return View();
        }
    </code>
  </pre>
</div>

<div class="row">
  <p>Server responses with search result and renders <i>query</i> parameter.</p>
  <pre>
    <code class="html">
        &lt;div class="row"&gt;
          @@if(ViewData["query"] != null) {
          &lt;div class="well text-center"&gt;@@Html.Raw((string)ViewData["query"])&lt;/div&gt;
          } else {
          &lt;div class="well text-center"&gt;
            &lt;span&gt;Search Results&lt;/span&gt;
          &lt;/div&gt;
          }
        &lt;/div&gt;      
    </code>
  </pre>

</div>

<!-- Search form -->
<div id="search">
  <button type="button" class="close">×</button>
  <form asp-controller="CrossSiteScripting" asp-action="DemoTypeII" method="get">
    <input name="query" type="search" value="" placeholder="type keyword(s) here" />
    <button type="submit" class="btn btn-primary">Search</button>
  </form>
</div>

@section Scripts {
<script>
  $('a[href="#search"]').on('click', function (event) {
    event.preventDefault();
    $('#search').addClass('open');
    $('#search > form > input[type="search"]').focus();
  });

  $('#search, #search button.close').on('click keyup', function (event) {
    if (event.target == this || event.target.className == 'close' || event.keyCode == 27) {
      $(this).removeClass('open');
    }
  });

  hljs.initHighlightingOnLoad();
</script>
}

Views/CrossSiteScripting/Index.cshtml
@{
    ViewData["Title"] = "Stored XSS";
}

<div class="row">
    <h1 class="text-center">Cross-Site Scripting (XSS)</h1>
</div>
<div class="row">
    <p>XSS flaws occur whenever an application includes untrusted data in a new web page without proper validation or escaping, or updates an existing web page with user supplied data using a browser API that can create JavaScript. XSS allows attackers to execute scripts in the victim’s browser which can hijack user sessions, deface web sites, or redirect the user to malicious sites.</p>
</div>

<div class="row">
    <h2>Stored XSS (AKA Persistent or Type I)</h2>
</div>
<div class="row">
    <p>Stored XSS generally occurs when user input is stored on the target server, such as in a database, in a message forum, visitor log, comment field, etc. And then a victim is able to retrieve the stored data from the web application without that data being made safe to render in the browser. With the advent of HTML5, and other browser technologies, we can envision the attack payload being permanently stored in the victim’s browser, such as an HTML5 database, and never being sent to the server at all.</p>
</div>
<div class="row">
    <ul>
        <li><a href="@Url.Action("DemoTypeI", "CrossSiteScripting")">Store and render unencoded HTML markup</a></li>
    </ul>
</div>

<div class="row">
    <h2>Reflected XSS (AKA Non-Persistent or Type II)</h2>
</div>
<div class="row">
    <ul>
        <li><a href="@Url.Action("DemoTypeII", "CrossSiteScripting")">Malicious parameter is reflected back to the user</a></li>
    </ul>
</div>

<div class="row">
    <p>Reflected XSS occurs when user input is immediately returned by a web application in an error message, search result, or any other response that includes some or all of the input provided by the user as part of the request, without that data being made safe to render in the browser, and without permanently storing the user provided data. In some cases, the user provided data may never even leave the browser (see DOM Based XSS next).</p>
</div>

<div class="row">
    <h2>DOM Based XSS (AKA Type-0)</h2>
</div>
<div class="row">
    <p>As defined by Amit Klein, who published the first article about this issue[1], DOM Based XSS is a form of XSS where the entire tainted data flow from source to sink takes place in the browser, i.e., the source of the data is in the DOM, the sink is also in the DOM, and the data flow never leaves the browser. For example, the source (where malicious data is read) could be the URL of the page (e.g., document.location.href), or it could be an element of the HTML, and the sink is a sensitive method call that causes the execution of the malicious data (e.g., document.write)."</p>
</div>

Views/Home/Index.cshtml
@{ 
  ViewData["Title"] = "Home Page"; 
}

<div class="row text-center">
  <h1>VulnerableCoreApp Conent</h1>
</div>

<div class="row">
  <ul>
    <li>
      <a asp-area="" asp-controller="CrossSiteScripting" asp-action="Index">Cross-Site Scripting (XSS)</a>
      <ul>
        <li>
          <a asp-area="" asp-controller="CrossSiteScripting" asp-action="DemoTypeI">Store and render unencoded HTML markup</a>
        </li>
        <li>
          <a asp-area="" asp-controller="CrossSiteScripting" asp-action="DemoTypeII">Malicious parameter is reflected back to the user</a>
        </li>
      </ul>
    </li>
  </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VulnerableCoreApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/vs2015.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">VulnerableCoreApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; 2017 - VulnerableCoreApp | This application is influenced by OWASP Top Ten Project and contains texts that can be found on <a href="https://www.owasp.org">OWASP web pages</a>
            </p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>